export enum EventName {
  zimError = "error",
  zimConnectionStateChanged = "connectionStateChanged",
  zimTokenWillExpire = "tokenWillExpire",
  zimReceivePeerMessage = "receivePeerMessage",
  zimReceiveGroupMessage = "receiveGroupMessage",
  zimConversationTotalUnreadMessageCountUpdated = "conversationTotalUnreadMessageCountUpdated",
  zimConversationChanged = "conversationChanged",
  zimGroupMemberStateChanged = 'groupMemberStateChanged',
  zimKitLoginStateChanged = 'loggedStateChanged',
  zimKitLoginUserUpdate = "loginUserUpdate",
  zimKitDeleteConversation = "deleteConversation",
  zimKitCurrentConversationChanged = 'currentConversationChanged',
  zimKitCurrentConversationUpdate = "currentConversationUpdate",
  zimKitConversationListUpdate = "conversationListUpdate",
  zimKitConversationListQueryAbnormally = "conversationListQueryAbnormally",
  zimKitCurrentChatChanged= "currentChatChanged",
  zimKitCurrentChatUpdated = "currentChatUpdated",
  zimKitCurrentGroupInfoUpdated = "currentGroupInfoUpdated",
  zimKitImgMessageUpdated = "imgMessageUpdated",
  zimKitNetworkChanged = 'networkChanged',
  zimKitModeChanged = 'modeChanged',
}
